version: '3.8'
services:
  setup:
    build: ./setup
    depends_on:
      - nats
  nats:
    image: nats:latest
    command: ["-js"]
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
      
  publisher:
    build: ./publisher
    depends_on:
      - nats
      - setup
    volumes:
      - ./publisher:/app
      
  publisher2:
    build: ./publisher
    depends_on:
      - nats
      - setup
    volumes:
      - ./publisher:/app
  publisher3:
    build: ./publisher
    depends_on:
      - nats
      - setup
    volumes:
      - ./publisher:/app


  subscriber:
    build: ./subscriber
    depends_on:
      - nats
      - setup
    volumes:
      - ./subscriber/:/app
      
